sudo: required
services:
  - docker
language: python
python:
  - "3.6"
before_install:
  - docker build -t blgo/flask-realtime-restapi .
  - docker run --name realtimeapp -d -p 80:80 blgo/flask-realtime-restapi
  - docker run --name mongo --link realtimeapp:mongo -d mongo:3.6.2
  - docker ps -a
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose
# Run tests
script:
  - nosetests
  - python tests/integration.py
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push blgo/flask-realtime-restapi;
    fi
